spring:

  datasource:
    url: "${DATABASE_URL}"
    username: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

    show-sql: true

  ai:
    ollama:
      chat:
        options:
          model: llama3.2:3b

  security:
    secret-key: "${SECURITY_SECRET_KEY}"
    expiration: 86400000
    oauth2:
      client:
        registration:
          google:
            client-name: "${OAUTH_CLIENT_NAME}"
            client-id: "${OAUTH_CLIENT_ID}"
            client-secret: "${OAUTH_CLIENT_SECRET}"
            scope:
              - email
              - profile

  app:
    oauth2:
      redirect-url: "/user-info"

  mail:
    username: "${MAIL_USERNAME}"
    password: "${MAIL_PASSWORD}"

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

